### ISSUE TITLE
Broken documentation, can't get started with this project

### ISSUE THREAD

**Issue by dgtlmoon** [darrenburns/ward#178]
So after a few hours of frustration, the ward project didnt work with my existing Flask application, so I decided to go back to basics.

From https://wardpy.com/guide/testing-flask , I copied the code..

```
from flask import Flask
app = Flask(__name__)
@app.route("/users/<str:username>")
def get_user(username: str):
    return f"The user is {username}"
    
if __name__ == '__main__':
    app.run()

```

I get

```
root@3ecd35801f44:/x# python -m users.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/x/users.py", line 4, in <module>
    def get_user(username: str):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1278, in add_url_rule
    self.url_map.add(rule)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 1482, in add
    rule.bind(self)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 767, in bind
    self.compile()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 836, in compile
    _build_regex(self.rule if self.is_leaf else self.rule.rstrip("/"))
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 825, in _build_regex
    convobj = self.get_converter(variable, converter, c_args, c_kwargs)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 775, in get_converter
    raise LookupError("the converter %r does not exist" % converter_name)
LookupError: the converter 'str' does not exist
```

When I try the `test_users.py`, which looks like

```
from ward import fixture
from users import app
@fixture
def test_client():
    app.config['TESTING'] = True  # For better error reports    
    with app.test_client() as client:
        yield client

@test("/users/alice returns an 200 OK")
def _(client=test_client):
    res = client.get("/users/alice")
    assert res.data == "The user is alice"
```
I get

```


root@3ecd35801f44:/x# ward
Traceback (most recent call last):
  File "/usr/local/bin/ward", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ward/run.py", line 143, in test
    modules = list(load_modules(mod_infos))
  File "/usr/local/lib/python3.9/site-packages/ward/collect.py", line 119, in load_modules
    m.__loader__.exec_module(m)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./test_users.py", line 2, in <module>
    from users import app
  File "./users.py", line 4, in <module>
    def get_user(username: str):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1278, in add_url_rule
    self.url_map.add(rule)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 1482, in add
    rule.bind(self)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 767, in bind
    self.compile()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 836, in compile
    _build_regex(self.rule if self.is_leaf else self.rule.rstrip("/"))
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 825, in _build_regex
    convobj = self.get_converter(variable, converter, c_args, c_kwargs)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 775, in get_converter
    raise LookupError("the converter %r does not exist" % converter_name)
LookupError: the converter 'str' does not exist

```

**Comment by dgtlmoon** [comment]
I believe this is a `python 2` reference...

https://github.com/flask-restful/flask-restful/issues/537

**Comment by dgtlmoon** [comment]
Another issue in the documentation..
![image](https://user-images.githubusercontent.com/275001/107776738-3d617b80-6d42-11eb-9329-0bd1365296e5.png)

Wrong..

```
root@3ecd35801f44:/x# python -m users.py
/usr/local/bin/python: Error while finding module specification for 'users.py' (ModuleNotFoundError: __path__ attribute not found on 'users' while trying to find 'users.py'). Try using 'users' instead of 'users.py' as the module name.
root@3ecd35801f44:/x# python -m users
 * Serving Flask app "users" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

**Comment by dgtlmoon** [comment]
And then after all of this...


```
Traceback (most recent call last):
  File "/usr/local/bin/ward", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ward/run.py", line 143, in test
    modules = list(load_modules(mod_infos))
  File "/usr/local/lib/python3.9/site-packages/ward/collect.py", line 119, in load_modules
    m.__loader__.exec_module(m)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./test_users.py", line 11, in <module>
    @test("/users/alice returns an 200 OK")
NameError: name 'test' is not defined
```
