### ISSUE TITLE
Running tests with Python 3.11.0 yields ValueError during rewrite_assertion

### ISSUE THREAD

**Issue by AndydeCleyre** [darrenburns/ward#352]
The tests of [NestedTextTo](https://github.com/AndydeCleyre/nestedtextto) run without problem with Python 3.7, 3.8, 3.9, and 3.10:
```console
$ podman run -it -e TERM=$TERM --rm docker.io/library/python:3.10 bash
# git clone 'https://github.com/AndydeCleyre/nestedtextto'
# cd nestedtextto
# git checkout 0.1.2
# pip install '.[test]'
# ward --version
ward, version 0.66.1b0
# ward
```
```
─────────────────────────────────────────────────────────────── Ward 0.66.1b0 | CPython 3.10.8 ───────────────────────────────────────────────────────────────
Loaded config from pyproject.toml.
Found 65 tests and 0 fixtures in 0.08 seconds.

test/test_json.py: .....................                                                                                                                   34%
test/test_toml.py: ....................                                                                                                                    65%
test/test_yaml.py: ........................                                                                                                               100%


╭───────────── Results ─────────────╮
│  65  Tests Encountered            │
│  65  Passes             (100.0%)  │
╰───────────────────────────────────╯
────────────────────────────────────────────────────────────────── SUCCESS in 0.24 seconds ───────────────────────────────────────────────────────────────────
```
The same raises a `ValueError` during `rewrite_assertion` when run with Python 3.11.0:
```console
$ podman run -it -e TERM=$TERM --rm docker.io/library/python:3.11 bash
# git clone 'https://github.com/AndydeCleyre/nestedtextto'
# cd nestedtextto
# git checkout 0.1.2
# pip install '.[test]'
# ward --version
ward, version 0.66.1b0
# ward
```
```python
Traceback (most recent call last):
  File "/usr/local/bin/ward", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ward/_run.py", line 207, in test
    tests = rewrite_assertions_in_tests(filtered_tests)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ward/_rewrite.py", line 90, in rewrite_assertions_in_tests
    return [rewrite_assertion(test) for test in tests]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ward/_rewrite.py", line 90, in <listcomp>
    return [rewrite_assertion(test) for test in tests]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ward/_rewrite.py", line 115, in rewrite_assertion
    new_mod_code_obj = compile(new_tree, code_obj.co_filename, "exec")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: line 46, column 71-68 is not a valid range
```

**Comment by AndydeCleyre** [comment]
I see the same happening running ward's own tests (master branch) with Python 3.11.0:

```python
Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/bin/ward", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/.local/share/venvs/115fcdd46e81abe262e531e3badbc43d/venv-python-3.11.0/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/Code/ward/ward/_run.py", line 207, in test
    tests = rewrite_assertions_in_tests(filtered_tests)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/Code/ward/ward/_rewrite.py", line 90, in rewrite_assertions_in_tests
    return [rewrite_assertion(test) for test in tests]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/Code/ward/ward/_rewrite.py", line 90, in <listcomp>
    return [rewrite_assertion(test) for test in tests]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andy/Code/ward/ward/_rewrite.py", line 115, in rewrite_assertion
    new_mod_code_obj = compile(new_tree, code_obj.co_filename, "exec")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: line 234, column 59-57 is not a valid range

```

**Comment by AndydeCleyre** [comment]
I found that ward's own tests pass on 3.11.0 if I comment out the re-indentation bit in `rewrite_assertion`:

```python
    for child in ast.walk(new_tree):
        if hasattr(child, "col_offset"):
            child.col_offset = getattr(child, "col_offset", 0) + col_offset
```

**Comment by AndydeCleyre** [comment]
Looks like a similar snag at akornatskyy/wheezy.template#68.

**Comment by AndydeCleyre** [comment]
Related:

- #354 
- #353
