### ISSUE TITLE
AttributeError: 'FileFinder' object has no attribute 'find_module' when running on python 3.12

### ISSUE THREAD

**Issue by tiagocoutinho** [darrenburns/ward#372]
1. on an empty directory created `test_example.py`:
```python
from ward import test

@test("simple addition")
def _():
    assert 1 + 2 == 3
```
2. created a conda environment with python 3.12: `conda create --name ward-py312 python=3.12`
3. activated the conda environment with `conda activate ward-py312`
4. installed latest ward with `pip install ward` (got ward-0.67.2b0)
5. ran `ward` and got:
```bash
$ ward                                                                                                                                                       Traceback (most recent call last):
  File "/home/coutinho/miniconda/envs/ward-py312/bin/ward", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_run.py", line 199, in test
    mod_infos = get_info_for_modules(paths, exclude)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 102, in get_info_for_modules
    if is_test_module(mod) and not _is_excluded_module(mod, exclude):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 34, in _is_excluded_module
    return _excluded(_get_module_path(module), exclusions)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coutinho/miniconda/envs/ward-py312/lib/python3.12/site-packages/ward/_collect.py", line 30, in _get_module_path
    return Path(module.module_finder.find_module(module.name).path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'

```

**Comment by taconi** [comment]
The method was deprecated [`find_module`](https://docs.python.org/3.10/library/importlib.html#importlib.abc.PathEntryFinder.find_module), I believe it would just be updated to `return Path(module.module_finder.find_spec(module. name).origin)`, the method [`find_spec`](https://docs.python.org/3.10/library/importlib.html#importlib.machinery.FileFinder.find_spec) was added in 3.4 so it would not give an error in currently maintained python versions.
I can send a pr with this adjustment.
